# Generated by Django 5.0.7 on 2024-07-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='group',
            new_name='category',
        ),
    ]
