# Generated by Django 5.0.7 on 2024-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_rename_group_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
